name: Build and deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npm ci --prefix client
      - run: npm ci --prefix functions

      - run: npm run build --prefix client
      - run: npm run build --prefix functions

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main'}}
        run: |
          npm install
          npm run firebase -- deploy --only hosting,functions --project "${{ secrets.FIREBASE_PROJECT }}" --token "${{ secrets.FIREBASE_TOKEN }}"
        env:
          REACT_APP_API_BASE_URL: https://asia-southeast2-secret-safe-space.cloudfunctions.net/api
          REACT_APP_URL: https://secret-safe-space.web.app
