name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install client dependencies
        run: npm --prefix client install
      - name: Install functions dependencies
        run: npm --prefix functions install
      - name: Deploy client and functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          REACT_APP_API_BASE_URL: https://asia-southeast2-shh-xyz.cloudfunctions.net/api
          REACT_APP_FIREBASE_CONFIG: '{"apiKey":"AIzaSyAFvEUThHw8DvbOHCFXO5AiAGDrRn9HSHQ","authDomain":"shh-xyz.firebaseapp.com","databaseURL":"https://shh-xyz.firebaseio.com","projectId":"shh-xyz","storageBucket":"shh-xyz.appspot.com","messagingSenderId":"227655520477","appId":"1:227655520477:web:5739a7f2027e86c15fcb34","measurementId":"G-GFV44QGE0R"}'
