name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install client dependencies
        run: npm --prefix client install
      - name: Install functions dependencies
        run: npm --prefix functions install
      - name: Deploy client and functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          REACT_APP_API_BASE_URL: https://asia-southeast2-shhh-83b92.cloudfunctions.net/api
          REACT_APP_FIREBASE_CONFIG: '{"apiKey":"AIzaSyA_D2uaIdMWS2-AbsSQIE_qdJSpEWMJ4eE","authDomain":"shhh-83b92.firebaseapp.com","databaseURL":"https://shhh-83b92.firebaseio.com","projectId":"shhh-83b92","storageBucket":"shhh-83b92.appspot.com","messagingSenderId":"395856542674","appId":"1:395856542674:web:13954f8453acc0885f660b","measurementId":"G-B64FK00HLZ"}'
